team-withiy/withiy-server

src/main/java/com/server/domain/oauth/service/AuthService.java, src/main/java/com/server/domain/oauth/service/GoogleLoginService.java, src/main/java/com/server/domain/user/repository/UserRepository.java, src/main/java/com/server/domain/user/service/UserService.java, src/main/java/com/server/global/jwt/JwtService.java
=> [Auth] JWT Token 생성 시 사용자의 이름이 아닌 PK (id) 사용하도록 변경

src/main/java/com/server/domain/oauth/controller/OAuthLoginController.java, src/main/java/com/server/domain/oauth/dto/KakaoTokenOutDto.java, src/main/java/com/server/domain/oauth/dto/KakaoUserOutDto.java, src/main/java/com/server/domain/oauth/entity/OAuth.java, src/main/java/com/server/domain/oauth/service/AuthService.java, src/main/java/com/server/domain/oauth/service/KakaoLoginService.java, src/main/resources/application-deploy.yaml, src/main/resources/application-test.yaml
+ oauth
+ FEAT: Kakao OAuth (resolves: #1)
=> feat: kakao oauth

src/main/java/com/server/domain/oauth/dto/OAuth2UserInfo.java, src/main/java/com/server/domain/oauth/handler/OAuth2SuccessHandler.java, src/main/java/com/server/domain/oauth/service/CustomOAuth2UserService.java, src/main/resources/application-deploy.yaml, src/main/resources/application-test.yaml
+ oauth2
+ FEAT: naver OAuth2 with spring security (resolves: #9)
http://localhost:8080/oauth2/authorization/naver  
-> 네이버 로그인
=> refactor: naver OAuth2 w Spring Security

src/main/java/com/server/domain/oauth/dto/OAuth2UserInfo.java, src/main/java/com/server/domain/oauth/entity/OAuth.java, src/main/java/com/server/domain/oauth/handler/OAuth2SuccessHandler.java, src/main/java/com/server/domain/oauth/repository/OAuthRepository.java, src/main/java/com/server/domain/oauth/service/CustomOAuth2UserService.java, src/main/java/com/server/global/config/SecurityConfig.java, src/main/resources/application-deploy.yaml, src/main/resources/application-test.yaml
+ `oauth`
+ OAuth2 과정에서 누락된 redirect uri 및 refresh token 추가 (resolves: #9)
=> fix: redirect uri & refresh token

src/main/java/com/server/domain/category/dto/CategoryDto.java, src/main/java/com/server/domain/category/entity/Category.java, src/main/java/com/server/domain/course/dto/CourseDto.java, src/main/java/com/server/domain/course/entity/Course.java, src/main/java/com/server/domain/course/entity/CoursePlace.java, src/main/java/com/server/domain/place/dto/PlaceDto.java, src/main/java/com/server/domain/place/entity/Place.java, src/main/java/com/server/domain/section/controller/SectionController.java, src/main/java/com/server/domain/section/dto/SectionDto.java, src/main/java/com/server/domain/section/entity/Section.java, src/main/java/com/server/domain/section/entity/SectionCourse.java, src/main/java/com/server/domain/section/entity/SectionCourseId.java, src/main/java/com/server/domain/section/entity/SectionPlace.java, src/main/java/com/server/domain/section/entity/SectionPlaceId.java, src/main/java/com/server/domain/section/repository/SectionCourseRepository.java, src/main/java/com/server/domain/section/repository/SectionPlaceRepository.java, src/main/java/com/server/domain/section/repository/SectionRepository.java, src/main/java/com/server/domain/section/service/SectionService.java
+ home section
+ FEAT: home section 개발 (resolves: #15)
http://localhost:8080/api/home/section 
isHome=true인 섹션 정보 제공
example)
{
"status": 0,
"message": "string",
"data": [
{
"title": "string",
"categoryDto": {
"id": 0,
"name": "string"
},
"places": [
{
"name": "string",
"address": "string",
"latitude": "string",
"longitude": "string",
"categoryId": 0
}
],
"courses": [
{
"name": "string"
}
]
}
],
"timestamp": "2025-04-09T12:15:38.738Z"
}
=> feat: home section added

src/main/java/com/server/domain/oauth/repository/OAuthRepository.java, src/main/java/com/server/domain/section/entity/SectionPlace.java, src/main/java/com/server/domain/section/repository/SectionCourseRepository.java, src/main/java/com/server/domain/section/repository/SectionPlaceRepository.java, src/main/java/com/server/domain/section/repository/SectionRepository.java, src/main/java/com/server/domain/user/repository/UserRepository.java
=> :hammer: fix: repository layser dtype

src/main/java/com/server/domain/category/controller/CategoryController.java, src/main/java/com/server/domain/category/dto/CategoryDto.java, src/main/java/com/server/domain/category/dto/CreateCategoryDto.java, src/main/java/com/server/domain/category/entity/Category.java, src/main/java/com/server/domain/category/repository/CategoryRepository.java, src/main/java/com/server/domain/category/service/CategoryService.java, src/main/java/com/server/domain/course/dto/CourseDto.java, src/main/java/com/server/domain/place/dto/PlaceDto.java, src/main/java/com/server/domain/section/controller/SectionController.java, src/main/java/com/server/domain/section/dto/CreateSectionDto.java, src/main/java/com/server/domain/section/dto/SectionCourseDto.java, src/main/java/com/server/domain/section/dto/SectionDto.java, src/main/java/com/server/domain/section/dto/SectionPlaceDto.java, src/main/java/com/server/domain/section/entity/Section.java, src/main/java/com/server/domain/section/entity/SectionCourse.java, src/main/java/com/server/domain/section/entity/SectionPlace.java, src/main/java/com/server/domain/section/repository/SectionCourseRepository.java, src/main/java/com/server/domain/section/repository/SectionPlaceRepository.java, src/main/java/com/server/domain/section/service/SectionService.java, src/main/java/com/server/global/error/code/CategoryErrorCode.java
+ Section
+ FEAT: section api (resolves: #15)
섹션 추가 api 개발
=> feat: section add api

src/main/java/com/server/domain/category/controller/CategoryController.java, src/main/java/com/server/domain/category/dto/CategoryDto.java, src/main/java/com/server/domain/category/dto/CreateCategoryDto.java, src/main/java/com/server/domain/category/entity/Category.java, src/main/java/com/server/domain/category/service/CategoryService.java, src/main/java/com/server/domain/course/dto/CoursePlaceDto.java, src/main/java/com/server/domain/course/entity/Course.java, src/main/java/com/server/domain/place/entity/Place.java, src/main/java/com/server/domain/section/controller/SectionController.java, src/main/java/com/server/domain/section/dto/CreateSectionDto.java, src/main/java/com/server/domain/section/dto/HomeSectionDto.java, src/main/java/com/server/domain/section/dto/SectionCourseDto.java, src/main/java/com/server/domain/section/dto/SectionPlaceDto.java, src/main/java/com/server/domain/section/entity/Section.java, src/main/java/com/server/domain/section/service/SectionService.java
+ dtos 수정
+ FEAT: dto 수정 (resolves: #20)
=> refactor: refactor dtos

src/main/java/com/server/global/error/handler/GlobalExceptionHandler.java
+ 별도의 exception handler 개발하여 해결 (resolves: #22)
=> :bug: fix: access denied exception

src/main/java/com/server/domain/section/controller/SectionController.java
+ sections
+ FEAT: GET home sections api authorization deleted (resolves: #28 )
=> refactor: get home sections api authorization deleted

src/main/java/com/server/domain/oauth/controller/OAuthController.java, src/main/java/com/server/domain/oauth/service/AuthService.java
+ `oauth`
+ status code 수정
+ frontend redirect uri 수정
=> chore: oauth 경로 수정

src/main/java/com/server/global/jwt/JwtAuthenticationFilter.java
+ Access token 인증 실패 시 500 -> 401 (resolves: #31)
=> :hammer: fix: http status code

src/main/java/com/server/domain/event/repository/EventRepository.java, src/main/java/com/server/domain/event/service/EventService.java
+ Event
+ FEAT: 기존 저장된 이벤트는 유지, 새로운 이벤트 정보 저장 (resolves: #53)
=> feat: save new events

src/main/java/com/server/domain/event/controller/EventController.java, src/main/java/com/server/domain/event/repository/EventRepository.java, src/main/java/com/server/domain/event/service/EventService.java, src/main/java/com/server/global/error/code/EventErrorCode.java
+ Event
+ FEAT: get event api(all, by genres(musical, concert, sports, exhibit, drama) (resolves: #54)
=> feat: get events api(all, by genres)

src/main/java/com/server/domain/event/dto/CrawlingEventDto.java, src/main/resources/application-test.yaml, src/test/java/com/server/domain/event/controller/EventControllerTest.java
+ Event 
+ FEAT: EventController 테스트 코드 개발
=> test: event test code

src/test/java/com/server/domain/event/controller/EventControllerTest.java, src/test/java/com/server/domain/event/service/EventServiceTest.java
+ EventControllerTest, EventServiceTest
+ FEAT: 테스트 코드에 장르별 이벤트 가져오기 부분 검증 (resolves: #73)
=> test: event controller, service test code added

src/main/java/com/server/domain/place/controller/PlaceController.java, src/main/java/com/server/domain/place/dto/PlaceDetailDto.java, src/main/java/com/server/domain/place/dto/PlaceImageDto.java, src/main/java/com/server/domain/place/entity/Place.java, src/main/java/com/server/domain/place/entity/PlaceImage.java, src/main/java/com/server/domain/place/repository/PlaceRepository.java, src/main/java/com/server/domain/place/service/PlaceService.java, src/main/java/com/server/global/error/code/PlaceErrorCode.java
+ PlaceDetail
+ FEAT: GET PlaceDetail api, 장소 상세 정보(
=> feat: get PlaceDetail api

src/main/java/com/server/domain/course/controller/CourseController.java, src/main/java/com/server/domain/course/dto/CourseDetailDto.java, src/main/java/com/server/domain/course/dto/CourseImageDto.java, src/main/java/com/server/domain/course/entity/Course.java, src/main/java/com/server/domain/course/entity/CourseBookmark.java, src/main/java/com/server/domain/course/entity/CourseImage.java, src/main/java/com/server/domain/course/repository/CourseBookmarkRepository.java, src/main/java/com/server/domain/course/repository/CourseRepository.java, src/main/java/com/server/domain/course/service/CourseService.java, src/main/java/com/server/domain/place/controller/PlaceController.java, src/main/java/com/server/domain/place/dto/PlaceDetailDto.java, src/main/java/com/server/domain/user/entity/User.java, src/main/java/com/server/global/error/code/CourseErrorCode.java
+ CourseDetail
+ FEAT: GET CourseDetail api 
결과 예시)
{
"status": 200,
"message": "Request processed successfully.",
"data": {
"name": "서울 데이트 코스",
"thumbnail": "https://example.com/course1.jpg",
"courseImageDtos": [
{
"imageUrl": "https://example.com/cimg1.jpg"
}
],
"placeDetailDtos": [
{
"name": "경복궁",
"address": "서울 종로구",
"latitude": "37.579617",
"longitude": "126.977041",
"categoryName": "명소",
"score": 95,
"placeImageDtos": [
{
"imageUrl": "https://example.com/pimg1.jpg"
}
]
}
]
},
"timestamp": "2025-05-14T17:37:33.447530091"
}
=> feat: get CourseDetail api

build.gradle, src/main/java/com/server/domain/user/controller/UserProfileController.java, src/main/java/com/server/domain/user/dto/ProfileImageResponseDto.java, src/main/java/com/server/domain/user/service/UserService.java, src/main/java/com/server/global/config/S3Config.java, src/main/java/com/server/global/service/S3Service.java, src/main/resources/application-deploy.yaml, src/main/resources/application-test.yaml, src/main/resources/application.yaml, src/test/java/com/server/global/config/TestS3Config.java, src/test/java/com/server/global/service/MockS3Service.java
This PR implements the AWS S3 service integration for file uploads in the application.
- Implemented S3Service for image upload and management
- Added S3Config for production environment
- Created TestS3Config and MockS3Service for test environment
- Updated UserService to use S3Service for profile images
- Added proper region configuration for S3 client (AP_NORTHEAST_2)
- Added comprehensive tests for S3Service functionality
Closes #72
=> [#72] S3 Service Implementation and Tests

src/main/java/com/server/domain/user/dto/CoupleDto.java, src/main/java/com/server/domain/user/dto/UserDto.java, src/main/java/com/server/global/config/S3UrlConfig.java, src/main/java/com/server/global/config/S3UrlInitializer.java, src/main/java/com/server/global/service/S3Service.java, src/main/resources/application-deploy.yaml, src/main/resources/application-test.yaml, src/test/java/com/server/global/service/MockS3Service.java
This PR implements CloudFront URL support for image delivery throughout the application to improve performance and reduce costs.
1. Added AWS S3 and CloudFront URL configurations to YAML files
2. Updated S3Service to use CloudFront URLs for image upload and deletion
3. Created S3UrlConfig for centralized URL management to avoid hardcoded URLs
4. Updated DTOs (UserDto, CoupleDto) to use CloudFront URLs when returning user thumbnails
5. Added placeholder files for future S3Service interface and integration tests
1. Check that GET /users/me returns CloudFront URL for user thumbnails
2. Verify that uploaded images are served via CloudFront URL
Resolves #90
=> Issue #90: Add CloudFront URL support for image delivery

src/main/java/com/server/domain/user/dto/UserProfileResponseDto.java, src/main/java/com/server/domain/user/service/UserService.java
프로필 조회 응답에 커플 유무 정보(hasCouple)를 포함하도록 리팩토링
Resolves #108
=> refactor: 프로필 조회 응답에 커플 유무 정보 추가

src/main/java/com/server/domain/album/entity/Album.java, src/main/java/com/server/domain/category/entity/Category.java, src/main/java/com/server/domain/photo/entity/Photo.java, src/main/java/com/server/domain/place/entity/Place.java
+ Place, Photo, Album
+ REFACTOR: 장소 삭제 시 연관관계 가지는 사진, 앨범 삭제되는 부분 수정
=> refactor: edit delete cascadetype [Place, Photo, Album]

src/main/java/com/server/domain/photo/entity/Photo.java, src/main/java/com/server/domain/review/entity/Review.java
+ Review, Photo
+ FEAT: review가 삭제되어도 사진은 삭제되지 않게 OnDelete action 추가
=> feat: review & photo ondelete action

src/main/java/com/server/domain/album/entity/Album.java, src/main/java/com/server/domain/album/repository/AlbumRepository.java, src/main/java/com/server/domain/album/service/AlbumService.java, src/main/java/com/server/domain/category/entity/Category.java, src/main/java/com/server/domain/category/repository/CategoryRepository.java, src/main/java/com/server/domain/photo/controller/PhotoController.java, src/main/java/com/server/domain/photo/dto/PhotoDto.java, src/main/java/com/server/domain/photo/entity/Photo.java, src/main/java/com/server/domain/photo/service/PhotoRepository.java, src/main/java/com/server/domain/photo/service/PhotoService.java, src/main/java/com/server/domain/place/controller/PlaceController.java, src/main/java/com/server/domain/place/dto/CreatePlaceByUserDto.java, src/main/java/com/server/domain/place/dto/CreatePlaceDto.java, src/main/java/com/server/domain/place/dto/RegisterPlaceDto.java, src/main/java/com/server/domain/place/entity/Place.java, src/main/java/com/server/domain/place/repository/PlaceRepository.java, src/main/java/com/server/domain/place/service/PlaceService.java, src/main/java/com/server/domain/review/entity/Review.java, src/main/java/com/server/domain/review/repository/ReviewRepository.java, src/main/java/com/server/domain/review/service/ReviewService.java, src/main/java/com/server/domain/schedule/entity/Schedule.java, src/main/java/com/server/domain/user/entity/Couple.java, src/main/java/com/server/domain/user/entity/User.java, src/main/java/com/server/global/service/ImageService.java, src/main/java/com/server/global/service/ImageServiceImpl.java
+ Place, Album, Photo, 
+ FEAT: 사용자가 장소 최초 등록/등록되어 있는 장소 등록 api
장소 등록 시 사진, 앨범, 리뷰가 연관되어 저장됨
api url 등 정리 참고
[https://www.notion.so/rldnd/208fd2520c8380e4abfad5609e17b67b](url)
=> feat: register & create place

src/main/java/com/server/domain/user/controller/UserController.java, src/main/java/com/server/domain/user/dto/NotificationSettingsDto.java, src/main/java/com/server/domain/user/entity/User.java, src/main/java/com/server/domain/user/service/UserService.java, src/test/java/com/server/domain/user/controller/UserControllerTest.java, src/test/java/com/server/domain/user/service/UserServiceTest.java
- 마이페이지 알림(데이트 알림, 이벤트 알림) 설정 API 구현
---
Related to #110
=> feat(user): 마이페이지 알림 설정 API

src/main/java/com/server/domain/user/controller/UserController.java, src/main/java/com/server/domain/user/dto/NotificationSettingsDto.java, src/main/java/com/server/domain/user/entity/User.java, src/main/java/com/server/domain/user/service/UserService.java, src/test/java/com/server/domain/user/controller/UserControllerTest.java, src/test/java/com/server/domain/user/service/UserServiceTest.java
=> refactor(user): 프로필 수정 API를 PATCH 메서드로 변경

src/main/java/com/server/domain/user/service/UserService.java, src/test/java/com/server/domain/user/service/UserServiceTest.java
+ 유저 탈퇴
+ FIX: 유저 탈퇴 시 커플 연결 해제되지 않도록 수정 (related to #141)
=> fix: 유저 탈퇴 시 커플 연결 해제되지 않도록 수정

src/main/java/com/server/domain/oauth/dto/OAuth2UserInfo.java, src/main/java/com/server/domain/oauth/entity/OAuth.java, src/main/java/com/server/domain/oauth/repository/OAuthRepository.java, src/main/java/com/server/domain/oauth/service/OAuth2UserService.java, src/main/java/com/server/domain/user/controller/UserController.java, src/main/java/com/server/domain/user/entity/User.java, src/main/java/com/server/domain/user/service/UserService.java, src/test/java/com/server/domain/user/service/UserServiceTest.java
계정 리셋 시, 사용자 프로필이 최초 소셜 로그인 시점의 닉네임과 썸네일로 초기화되도록 수정했습니다.
---
Related to #141
---
계정 리셋 시 초기 프로필 정보를 복구할 수 있도록, 소셜 로그인 시점의 `nickname`, `thumbnail` 값을 OAuth 테이블에 저장하도록 수정했습니다.
**OAuth.java**
```java
@Entity
@EntityListeners(AuditingEntityListener.class)
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "oauth")
public class OAuth {
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
@Column(name = "id")
private Long id;
@Column(name = "provider")
private String provider;
@Column(name = "provider_id")
private String providerId;
@Column(name = "email")
private String email;
@Column(name = "nickname")
private String nickname;
@Column(name = "thumbnail")
private String thumbnail;
// NOTE: OAuth 저장 시 User도 함께 저장되도록
@ManyToOne(cascade = CascadeType.PERSIST)
@JoinColumn(name = …
```
=> fix: 계정 리셋 시, 사용자 프로필이 최초 소셜 로그인 시점의 닉네임과 썸네일로 초기화되도록 수정

src/main/java/com/server/domain/badge/dto/BadgeResponseDto.java, src/main/java/com/server/domain/badge/dto/BadgeSelectionRequestDto.java, src/main/java/com/server/domain/badge/entity/Badge.java, src/main/java/com/server/domain/badge/entity/UserBadge.java, src/main/java/com/server/domain/badge/service/BadgeService.java, src/main/java/com/server/global/error/BadgeErrorCode.java, src/main/java/com/server/global/error/exception/BadgeException.java, src/test/java/com/server/domain/badge/controller/BadgeController.java, src/test/java/com/server/domain/badge/controller/BadgeControllerTest.java, src/test/java/com/server/domain/badge/service/BadgeServiceTest.java
+ BADGE
+ TEST: 배지 관련 기능 성공 테스트 코드 작성 (resolves: #149)
=> Test: 배지 관련 기능 성공 테스트 코드 작성

src/main/java/com/server/domain/search/dto/BookmarkedCourseDto.java, src/main/java/com/server/domain/search/dto/BookmarkedPlaceDto.java, src/main/java/com/server/domain/search/dto/SearchHistoryDto.java
+ Search
+ CHORE: dto에 swagger 주석 추가 (resolves: #153)
=> chore: dto에 swagger 주석 추가

src/main/java/com/server/domain/user/dto/UserDto.java, src/test/java/com/server/domain/user/service/UserServiceTest.java
+ COUPLE
+ CHORE: 복구 가능 커플 정보 DTO 이름 수정(`restorableCoupleDto` -> `restorableCouple`)(resolves: #157)
=> chore: 복구 가능 커플 정보 DTO 이름 수정

src/main/java/com/server/domain/admin/service/AdminFacade.java, src/main/java/com/server/domain/album/service/AlbumService.java, src/main/java/com/server/domain/photo/controller/PhotoController.java, src/main/java/com/server/domain/photo/dto/PhotoDto.java, src/main/java/com/server/domain/photo/entity/Photo.java, src/main/java/com/server/domain/photo/service/PhotoRepository.java, src/main/java/com/server/domain/photo/service/PhotoService.java, src/main/java/com/server/domain/place/controller/PlaceController.java, src/main/java/com/server/domain/place/dto/GetPlaceDetailResponse.java, src/main/java/com/server/domain/place/dto/LocationDto.java, src/main/java/com/server/domain/place/entity/Place.java, src/main/java/com/server/domain/place/repository/PlaceBookmarkRepository.java, src/main/java/com/server/domain/place/service/PlaceFacade.java, src/main/java/com/server/domain/place/service/PlaceService.java, src/main/java/com/server/domain/review/dto/ReviewDto.java, src/main/java/com/server/domain/review/entity/Review.java, src/main/java/com/server/domain/review/repository/ReviewRepository.java, src/main/java/com/server/domain/review/service/ReviewService.java, src/main/java/com/server/domain/user/dto/SimpleUserDto.java, src/test/java/com/server/domain/admin/AdminFacadeTest.java
<h2><strong>🔧</strong> 변경 사항</h2>
<ul>
<li><code>GET /api/places/detail/{placeId}</code> API 작업 완료</li>
</ul>
<h2><strong>⚠️</strong> 특이 사항</h2>
<ul>
<li><code>GET /api/places/detail/{placeId}</code> API 테스트 필요함</li>
</ul>
<pre><code class="language-jsx">{
&quot;status&quot;: 0,
&quot;message&quot;: &quot;string&quot;,
&quot;data&quot;: {
&quot;placeId&quot;: 1,
&quot;placeName&quot;: &quot;맥도날드 강남점&quot;,
&quot;categoryName&quot;: &quot;패스트푸드&quot;,
&quot;address&quot;: &quot;서울특별시 강남구 테헤란로 123&quot;,
&quot;location&quot;: {
&quot;latitude&quot;: &quot;string&quot;,
&quot;longitude&quot;: &quot;string&quot;,
&quot;region1depth&quot;: &quot;string&quot;,
&quot;region2depth&quot;: &quot;string&quot;,
&quot;region3depth&quot;: &quot;string&quot;
},
&quot;score&quot;: 81,
&quot;photos&quot;: …
=> Issue#166/refactor/place

src/main/java/com/server/domain/place/dto/GetPlaceDetailResponse.java, src/main/java/com/server/domain/place/service/PlaceFacade.java
+ Place
+ FEAT: [CONTENTS](fix:) (resolves: #170)
=> fix: isBookmarked는 비로그인 사용자 시 불필요하므로 제거

src/main/java/com/server/domain/place/service/PlaceFacade.java, src/main/java/com/server/domain/review/dto/ReviewDto.java
+ PLACE
+ REFACTOR: 장소 리뷰 정보에 장소 이름 정보 추가 (resolves: #179)
=> refactor: 장소 리뷰 정보에 장소 이름 정보 추가

src/main/java/com/server/domain/folder/controller/FolderController.java
+ FOLDER
+ FIX: 폴더에 장소 저장 API HTTP 메소드 GET에서 POST로 수정 (resolves: #177)
=> Issue##177/feat/folder

src/main/java/com/server/domain/folder/controller/FolderController.java, src/main/java/com/server/domain/folder/dto/FolderOptionDto.java, src/main/java/com/server/domain/folder/dto/FolderSummaryDto.java, src/main/java/com/server/domain/folder/entity/Folder.java, src/main/java/com/server/domain/folder/entity/FolderColor.java, src/main/java/com/server/domain/folder/entity/FolderType.java, src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java, src/main/java/com/server/domain/folder/service/FolderFacade.java, src/main/java/com/server/domain/folder/service/FolderService.java, src/main/java/com/server/domain/place/service/PlaceFacade.java, src/main/java/com/server/domain/user/service/UserService.java, src/main/java/com/server/global/error/code/FolderErrorCode.java, src/test/java/com/server/domain/user/service/UserServiceTest.java
- [GET /api/folders/select 추가](https://discord.com/channels/1346418754439086100/1403725798065700936/1408081170733858978)
- [기존 GET /api/folders 변경](https://discord.com/channels/1346418754439086100/1403725798065700936/1408081605116956692)
-  [내 장소 폴더 디폴트로 생성 및 삭제 금지 처리](https://discord.com/channels/1346418754439086100/1403725798065700936/1408082512592244807)
---
Resolves #187
=> Issue#187/fix/folder place

src/main/java/com/server/domain/folder/controller/FolderController.java, src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java, src/main/java/com/server/domain/folder/service/FolderFacade.java, src/main/java/com/server/domain/place/repository/PlaceRepository.java, src/main/java/com/server/domain/place/service/PlaceService.java, src/main/java/com/server/global/pagination/dto/ApiCursorPaginationRequest.java, src/main/java/com/server/global/pagination/utils/CursorPaginationUtils.java
- ApiCursorPaginationRequest에 Setter 추가하여 @ModelAttribute 매핑 가능하도록 수정
- prev 요청 시 subList 처리 방식을 분기하여 올바른 데이터 반환 보장
=> fix: 커서 기반 페이징 처리 로직 수정

http/http-client.env.json, src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java, src/main/java/com/server/domain/place/service/PlaceService.java, src/main/java/com/server/global/pagination/utils/CursorPaginationUtils.java, src/main/resources/application-deploy.yaml
- subList 인덱스 범위 안전하게 보정 (Math.max / Math.min)
- JPA 쿼리에 Pageable 인자 추가하여 limit+1 조회 처리
- 실제 반환 데이터는 limit까지만 잘라내도록 개선
=> fix: 커서 기반 페이징 limit 처리 버그 수정

src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java, src/main/java/com/server/domain/place/service/PlaceService.java, src/main/java/com/server/global/pagination/dto/ApiCursorPaginationRequest.java, src/main/java/com/server/global/pagination/utils/CursorPaginationUtils.java
- hasNext, hasPrev 잘못 계산되는 문제 수정
- cursor != null 조건만 사용 시 범위 밖 cursor 에서 오동작 발생
- DB 쿼리(EXISTS) 기반으로 실제 앞/뒤 데이터 존재 여부 확인하도록 변경
- total에는 전체 개수가 오도록 수정
=> Issue#196/feat/pagination

src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java, src/main/java/com/server/domain/map/controller/MapController.java, src/main/java/com/server/domain/map/dto/MapPlaceDto.java, src/main/java/com/server/domain/map/dto/response/CategorySearchResponse.java, src/main/java/com/server/domain/map/dto/response/KeywordSearchResponse.java, src/main/java/com/server/domain/map/service/MapService.java, src/main/java/com/server/domain/photo/service/PhotoService.java, src/main/java/com/server/domain/place/controller/PlaceController.java, src/main/java/com/server/domain/place/dto/LocationDto.java, src/main/java/com/server/domain/place/dto/request/NearbyPlaceRequest.java, src/main/java/com/server/domain/place/entity/Place.java, src/main/java/com/server/domain/place/repository/PlaceRepository.java, src/main/java/com/server/domain/place/service/PlaceFacade.java, src/main/java/com/server/domain/place/service/PlaceService.java, src/main/java/com/server/domain/route/repository/RouteBookmarkRepository.java, src/main/java/com/server/domain/search/controller/SearchController.java, src/main/java/com/server/domain/search/service/SearchFacade.java, src/main/java/com/server/domain/search/service/SearchFacadeService.java, src/main/java/com/server/global/error/handler/FilterChainExceptionHandler.java
데이터 일정 생성 페이지에서 장소 검색 시, 등록된 장소가 없다면 카카오 맵에서 장소 조회하도록 처리
Resolves #240
=> Issue#240/feat/kakao map

src/main/java/com/server/global/config/WebConfig.java
+ CORS
+ Fix: CORS 설정에 PATCH 메서드 허용 추가 (resolves: #249)
=> fix: CORS 설정에 PATCH 메서드 허용 추가
